### PR TITLE
Auth with CAS

### PR DESCRIPTION
**Pull request by dereknex**
support Apereo CAS auth;
PS: I have filled the CLA form.

### CODE REVIEW

**Comment by HarveyKandola** [comment]
Ready to merge?

**Comment by HarveyKandola** [comment]
I asked @sauls8t to update the database driver dependencies.

**Comment by dereknex** [comment]
@HarveyKandola Yes, It's ready.

**Comment by HarveyKandola** [comment]
So for the admin section:

* ```CAS Server URL``` points to the CAS installation
* ```Redirect URL``` is the Documize URL after login?

What happens if user authentication within CAS fails?

**Comment by HarveyKandola** [comment]
How are you syncing users with CAS and Documize?

We sync users between Documize and LDAP/Keycloak.

https://github.com/documize/community/blob/b6e1543b7f2ec2a1af397a4a62242f37e6014f43/domain/auth/ldap/endpoint.go#L130

**Comment by dereknex** [comment]
We can't sync users between Documize and CAS. 
This is CAS protocol: https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html
I can't find API for list users.

**Comment by dereknex** [comment]
I will add a README.md for CAS.

**Comment by dereknex** [comment]
Please don't merge this PR until the README.md has added. Thanks.

**Comment by HarveyKandola** [comment]
> We can't sync users between Documize and CAS.
> This is CAS protocol: https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html
> I can't find API for list users.

So we need to add users to Documize that have authenticated with CAS?

**Comment by dereknex** [comment]
> > We can't sync users between Documize and CAS.
> > This is CAS protocol: https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html
> > I can't find API for list users.
> 
> So we need to add users to Documize that have authenticated with CAS?

The user is automatically created when the user first login with CAS.

**Comment by HarveyKandola** [comment]
> > > We can't sync users between Documize and CAS.
> > > This is CAS protocol: https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html
> > > I can't find API for list users.
> > 
> > 
> > So we need to add users to Documize that have authenticated with CAS?
> 
> The user is automatically created when the user first login with CAS.

We need to set the following fields when creating a new user post-login:

* Email
* Firstname
* Lastname
* Initials

This is not sufficient:

```
		u.Email = userInfo.User
		u.Initials = stringutil.MakeInitials(userInfo.User, "")
```

**Comment by dereknex** [comment]
> > > > We can't sync users between Documize and CAS.
> > > > This is CAS protocol: https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html
> > > > I can't find API for list users.
> > > 
> > > 
> > > So we need to add users to Documize that have authenticated with CAS?
> > 
> > 
> > The user is automatically created when the user first login with CAS.
> 
> We need to set the following fields when creating a new user post-login:
> 
> * Email
> * Firstname
> * Lastname
> * Initials
> 
> This is not sufficient:
> 
> ```
> 		u.Email = userInfo.User
> 		u.Initials = stringutil.MakeInitials(userInfo.User, "")
> ```

I will change the logic to get Firstname and Lastname from user attributes.

**Comment by dereknex** [comment]
@HarveyKandola pls review again. thanks.

**Comment by HarveyKandola** [comment]
We have updated to improve the user attributes handling.

Not sure what editor you are coding with but please use ```gofmt``` on your code.

**Comment by dereknex** [comment]
I will use `gofmt` to my code

**Comment by HarveyKandola** [comment]
Also recommend that you provide CAS server setup instructions to help other contributors test this PR.

**Pull request merged**
